# Generated by Django 3.2.16 on 2022-10-06 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20221006_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='name',
        ),
    ]
