# Generated by Django 3.2.16 on 2022-10-06 12:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='tracks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(null=True), default=list, size=None),
        ),
    ]
