# Generated by Django 3.2.16 on 2022-10-06 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_artist_tracks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='website',
        ),
    ]
