# Generated by Django 3.2.16 on 2022-10-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_artist_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='artist',
            name='tracks',
        ),
        migrations.AddField(
            model_name='artist',
            name='tracks',
            field=models.ManyToManyField(to='core.Track'),
        ),
    ]
